# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#### Create an array of 10 ones

In [4]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
arr2 = arr1*5
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
arr3 = np.array(range(10,50))
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [9]:
arr4 = arr3[: :2]
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr5 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
arr6 = np.identity(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [22]:
 np.random.normal(0,1)


0.6938465320556257

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [31]:
 np.random.standard_normal(25)

array([-0.598382  , -1.88467566,  0.49479362,  0.21358537, -0.8698667 ,
        0.4161951 , -0.55005027,  0.32480394,  0.38376937,  1.22389498,
        1.38304504,  0.12361611,  0.30180859, -0.06577162,  0.95112594,
       -1.37082027, -0.02706819, -0.00495709,  0.82150059,  0.77791985,
        0.17943418,  0.2189235 , -0.45170748, -1.6266326 ,  0.43867958])


#Create an array of 20 linearly spaced points between 0 and 1:

In [30]:
np.random.normal(0,1,20)

array([ 2.17596771,  0.81804642,  0.0388454 ,  0.43318511,  0.1282694 ,
        0.726559  ,  1.29847796,  0.12326493, -0.3933866 , -0.73634414,
       -1.98620545, -2.19482745, -1.12641865,  0.49330428,  1.27853628,
       -0.80387925, -1.37595083, -2.36874253,  0.49230424, -1.04833017])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#find mean and std deviation of mat

In [25]:
mat.mean()

13.0

In [26]:
mat.std()

7.211102550927978

### Now do the following

#### Get the sum of all the values in mat

In [27]:
mat.sum()

325

# Great Job!